# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    path: homepage
    class: first
  - label: About me
    title: Who is TheTemportalist?
    path: page/2
  - label: Minecraft Mods
    title: The most up to date mods
    path: /page/mods-minecraft
    submenu:
      - label: mc-mods
        type: outerMenu
    class: last

social:
  - label: Twitter
    link: https://twitter.com/TheTemportalist
    icon: twitter
  - label: Player.me
    link: https://player.me/thetemportalist
    icon: player.me
  - label: Patreon
    link: https://www.patreon.com/TheTemportalist
    icon: patreon
  - label: GitHub
    link: https://github.com/TheTemportalist
    icon: github
  - label: CurseForge
    link: http://minecraft.curseforge.com/members/Country_Gamer/projects
    icon: curseforge
    submenu:
      - label: Jenkins
        link: http://jenkins.dries007.net/view/Temportal/
        icon: jenkins
        submenu:
          - label: Maven
            link: http://doubledoordev.net/maven/com/temportalist/
      - label: Bamboo
        link: http://ci.builtbroken.com:8085/browse/TEMP
        icon: bamboo
        submenu:
          - label: Maven
            link: http://ci.builtbroken.com/maven/com/temportalist/
  - label: Twitch
    link: http://www.twitch.tv/thetemportalist
    icon: twitch

mc-mods:
  - label: Origin
    path: /page/origin
    forge: 11.14.0.1289
    curseforge: 72503-origin
    buildserver: http://jenkins.dries007.net/view/Temportal/job/Origin/
    source: https://github.com/TheTemportalist/Origin
    maven: http://doubledoordev.net/maven|com.temportalist.origin:Origin:version
  - label: Weeping Angels
    path: /page/weeping-angels
    forge: 11.14.0.1289
    curseforge: a
  - label: Not Enough Keys
    path: /page/not-enough-keys
    forge: 11.14.0.1289
    curseforge: a
  - label: Tardis
    path: /page/tardis
    forge: 11.14.0.1289
    curseforge: a
  - label: Owner Emitter
    path: /page/owner-emitter
    forge: 11.14.0.1289
    curseforge: a
