# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    path: homepage
    class: first
  - label: About me
    title: Who is TheTemportalist?
    path: page/2
  - label: Projects
    title: Misc. Projects
    path: /page/projects
    submenu:
      - label: projects
        type: outerMenu
  - label: Minecraft Mods
    title: The most up to date mods
    path: /page/mods-minecraft
    submenu:
      - label: mc-mods
        type: outerMenu
      - label: Developer's
        submenu:
          - label: OriginGradle
          - label: Basic Setup
    class: last

social:
  - label: Twitter
    link: https://twitter.com/TheTemportalist
    icon: twitter
  - label: Player.me
    link: https://player.me/thetemportalist
    icon: player.me
  - label: Patreon
    link: https://www.patreon.com/TheTemportalist
    icon: patreon
  - label: GitHub
    link: https://github.com/TheTemportalist
    icon: github
  - label: CurseForge
    link: http://minecraft.curseforge.com/members/Country_Gamer/projects
    icon: curseforge
    submenu:
      - label: Jenkins
        link: http://jenkins.dries007.net/view/Temportal/
        icon: jenkins
        submenu:
          - label: Maven
            link: http://doubledoordev.net/maven/com/temportalist/
      - label: Bamboo
        link: http://ci.builtbroken.com:8085/browse/TEMP
        icon: bamboo
        submenu:
          - label: Maven
            link: http://ci.builtbroken.com/maven/com/temportalist/
  - label: Twitch
    link: http://www.twitch.tv/thetemportalist
    icon: twitch

projects:
  - label: Minecraft Mods
    path: /page/mods-minecraft
  - label: CurseForge Helper
    path: /page/cf-helper
  - label: Standalone Games
    path: /page/my-games

mc-mods:
  - label: Origin
    path: /page/origin
    curseforge: 72503-origin
    buildHost: jenkins
    buildLink: http://jenkins.dries007.net/view/Temportal/job/Origin/
    javadoc: null
    maven: http://doubledoordev.net/maven/|com.temportalist.origin:Origin:version
    sourceHost: github
    sourceLink: https://github.com/TheTemportalist/Origin
  - label: Weeping Angels
    path: /page/weeping-angels
    curseforge: 72505-weeping-angels
    buildHost: jenkins
    buildLink: http://jenkins.dries007.net/view/Temportal/job/WeepingAngels/
    sourceHost: github
    sourceLink: https://github.com/TheTemportalist/WeepingAngels
  - label: Not Enough Keys
    path: /page/not-enough-keys
    curseforge: 224614-notenoughkeys
    sourceHost: github
    sourceLink: https://github.com/mod-warriors/NotEnoughKeys
  - label: Tardis
    path: /page/tardis
    curseforge: a
    sourceHost: github
    sourceLink: https://github.com/TheTemportalist/Tardis
  - label: Secret Rooms
    path: /page/secret-rooms
    curseforge: 59652-seretroomsmod
    sourceHost: github
    sourceLink: https://github.com/mod-warriors/SecretRoomsMod-forge
  - label: Morph Additions
    path: /page/morph-additions
    curseforge: 223803-morphadditions
    sourceHost: github
    sourceLink: https://github.com/TheTemportalist/MorphAdditions
    buildHost: jenkins
    buildLink: http://jenkins.dries007.net/view/TheCountryGamer/job/MorphAdditions/
  - label: Owner Emitter
    path: /page/owner-emitter
    curseforge: 222818-owner-emitter
    sourceHost: github
    sourceLink: https://github.com/TheTemportalist/OwnerEmitter
