# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: About me
    title: Who is TheTemportalist?
    path: pages/about
    class: first
  - label: Minecraft Mods
    title: The most up to date mods
    path: pages/mods
    submenu:
      - label: Origin
        path: entry/3
      - label: Weeping Angels
        path: entry/4
      - label: Tardis
        path: entry/5
      - label: Secret Rooms
        path: entry/6
    class: last
