# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    path: homepage
    class: first
  - label: About me
    title: Who is TheTemportalist?
    path: page/2
  - label: Minecraft Mods
    title: The most up to date mods
    path: /page/mods-minecraft
    submenu:
      - label: Origin
        path: /page/mods-minecraft/origin
      - label: Weeping Angels
        path: /page/mods-minecraft/weeping-angels
      - label: Tardis
        path: /page/mods-minecraft/tardis
      - label: Secret Rooms
        path: /page/mods-minecraft/secret-rooms
    class: last
